name: "Vertex AI PR Reviewer"
description: "This GitHub Action automatically reviews PRs using Google's Gemini via Vertex AI."
author: 'merakiplace-developers'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token to interact with the repository'
    required: true
  VERTEXAI_CREDENTIALS_JSON:
    description: 'Google Cloud service account credentials (JSON)'
    required: true
  VERTEXAI_PROJECT_ID:
    description: 'GCP Project ID for Vertex AI'
    required: true
  EXCLUDE:
    description: 'Comma-separated list of file patterns to exclude'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt

    - name: Run Vertex AI Code Reviewer
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        VERTEXAI_CREDENTIALS_JSON: ${{ inputs.VERTEXAI_CREDENTIALS_JSON }}
        VERTEXAI_PROJECT_ID: ${{ inputs.VERTEXAI_PROJECT_ID }}
        INPUT_EXCLUDE: ${{ inputs.EXCLUDE }}
      run: python ${{ github.action_path }}/review_code_gemini.py